const MockFilmData = {
    actor: 'Dalton Keck',
    movies: [
      {
        keyId: 1,
        name: 'Earth Trailers',
        releaseDate: '2018-03-01T00:00:00.000Z',
        leadActor: 'Dalton Keck',
        subGenre: 'Zombies',
        producer: 'Tim Cook',
        iconColor: '#f00',
        toggle: 1,
      },
      {
        keyId: 2,
        name: 'Fly Again II',
        releaseDate: '2018-03-02T00:00:00.000Z',
        leadActor: 'Dalton Keck',
        subGenre: 'Insectoid',
        producer: 'Tim Cook',
        iconColor: '#0f0',
        toggle: 1,
      },
      {
        keyId: 3,
        name: 'AAAA',
        releaseDate: '2018-03-05T00:00:00.000Z',
        leadActor: 'Dalton Keck',
        subGenre: 'Nature',
        producer: 'Burt Reynolds',
        iconColor: '#ff0',
        toggle: 0,
      },
      {
        keyId: 4,
        name: 'BBBB',
        releaseDate: '2018-03-06T00:00:00.000Z',
        leadActor: 'Dalton Keck',
        subGenre: 'Nature',
        producer: 'Burt Reynolds',
        iconColor: '#0ff',
        toggle: 0,
      },
      {
        keyId: 5,
        name: 'Magma Eaters',
        releaseDate: '2018-03-18T00:00:00.000Z',
        leadActor: 'Dalton Keck',
        subGenre: 'Nature',
        producer: 'Burt Reynolds',
        iconColor: '#00f',
        toggle: 1,
      },
      {
        keyId: 6,
        name: 'CCC',
        releaseDate: '2018-03-20T00:00:00.000Z',
        leadActor: 'Dalton Keck',
        subGenre: 'Nature',
        producer: 'Burt Reynolds',
        iconColor: '#fff',
        toggle: 0,
      },
    ],
  };

export default MockFilmData;